name: Build
on: [push, pull_request]
defaults:
  run:
    shell: bash

env:
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
        target:
          - template_debug
          - template_release
        arch:
          - x86_32
          - x86_64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
      - name: Set up Python (for SCons)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install scons
        run: |
          python -m pip install scons==4.5.2
      - name: Cache SCons files and compiled files
        uses: actions/cache@v3
        with:
          path: |
            $SCONS_CACHE
            build/*.template_*
            lib/godot-cpp/gen
            lib/godot-cpp/src/**.template_*
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
      - name: Build artifact
        run: |
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_32-x86_64
          path: |
            addons/lua-gdextension/build/libluagdextension.linux.*

