name: Build
on: [push, pull_request]
defaults:
  run:
    shell: bash

env:
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache

jobs:
  build_linux:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [x86_64, x86_32]
        platform: [linux, windows]
        include:
          - platform: linux
            arch: x86_32
            name: Linux (x86_32)
            packages: [build-essential, g++-multilib, scons]
          - platform: linux
            arch: x86_64
            name: Linux (x86_64)
            packages: [build-essential, scons]
          - platform: windows
            arch: x86_64
            name: Windows (x86_64)
            packages: [build-essential, g++-mingw-w64, scons]
          - platform: windows
            arch: x86_32
            name: Windows (x86_32)
            packages: [build-essential, g++-mingw-w64, scons]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ${{ join(matrix.packages, ' ') }}
      - name: Cache SCons files and compiled files
        uses: actions/cache@v3
        with:
          path: |
            $SCONS_CACHE
            build/*.template_*
            lib/godot-cpp/gen/
            lib/godot-cpp/src/**/*.template_*
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
      - name: Build artifact
        run: |
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            addons/lua-gdextension/build/libluagdextension.*

  build_distribution_zip:
    name: Build distribution zip
    needs: [build_linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Copy artifacts to build folder
        run: cp -r ${{ steps.download.outputs.download-path }}/**/libluagdextension* addons/lua-gdextension/build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lua-gdextension
          path: |
            addons/lua-gdextension/LICENSE
            addons/lua-gdextension/*.gdextension
            addons/lua-gdextension/build/libluagdextension*

