name: Build
on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - template_debug
          - template_release
        arch:
          - x86_32
          - x86_64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
      - name: Set up Python (for SCons)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install scons
        run: |
          python -m pip install scons==4.5.2
      - name: Build artifact
        run: |
          scons platform=linux target=${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_32-x86_64
          path: |
            addons/lua-gdextension/build/libluagdextension.linux.*

