name: Build and Test
on: [push, pull_request]
defaults:
  run:
    shell: bash

env:
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache

jobs:
  build_linux:
    name: ${{ matrix.platform }} (${{ matrix.arch }}, ${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [x86_64, x86_32, arm64, arm32]
        platform: [linux, android]
        include:
          - platform: android
            scons-args: android_api_level=21
        exclude:
          - platform: linux
            arch: arm64
          - platform: linux
            arch: arm32
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup godot-cpp
        uses: ./lib/godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.platform }}
      - name: Cache SCons files
        uses: actions/cache@v4
        with:
          path: .scons-cache/
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}-${{ hashfiles('.gitmodules', 'src/**') }}
          restore-keys: |
            ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}-
      - name: Build artifact
        run: |
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=${{ matrix.target }} ${{ matrix.scons-args }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            addons/lua-gdextension/build/libluagdextension.*
  
  build_windows:
    name: ${{ matrix.platform }} (${{ matrix.arch }}, ${{ matrix.target }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [x86_64, x86_32, arm64]
        platform: [windows]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup godot-cpp
        uses: ./lib/godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.platform }}
          windows-compiler: msvc
      - name: Cache SCons files
        uses: actions/cache@v4
        with:
          path: .scons-cache/
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}-${{ hashfiles('.gitmodules', 'src/**') }}
          restore-keys: |
            ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}-
      - name: Build artifact
        run: |
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=${{ matrix.target }} ${{ matrix.scons-args }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            addons/lua-gdextension/build/libluagdextension.*
          
  build_web:
    name: web (wasm32, ${{ matrix.target }}, ${{ matrix.threads && 'threads' || 'nothreads' }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        threads: [true, false]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup godot-cpp
        uses: ./lib/godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: web
      - name: Cache SCons files
        uses: actions/cache@v4
        with:
          path: .scons-cache/
          key: web-wasm32-${{ matrix.target }}-${{ matrix.threads && 'threads' || 'nothreads' }}-${{ hashfiles('.gitmodules', 'src/**') }}
          restore-keys: |
            web-wasm32-${{ matrix.target }}-${{ matrix.threads && 'threads' || 'nothreads' }}-
      - name: Build artifact
        run: |
          scons platform=web arch=wasm32 target=${{ matrix.target }} threads=${{ matrix.threads }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-wasm32-${{ matrix.target }}-${{ matrix.threads && 'threads' || 'nothreads' }}
          path: |
            addons/lua-gdextension/build/libluagdextension.*

  build_macos:
    name: ${{ matrix.platform }} (${{ matrix.arch }}, ${{ matrix.target }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [universal]
        platform: [macos, ios]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          brew install scons
      - name: Cache SCons files
        uses: actions/cache@v4
        with:
          path: .scons-cache/
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}-${{ hashfiles('.gitmodules', 'src/**') }}
          restore-keys: |
            ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}-
      - name: Build artifact
        run: |
          scons platform=${{ matrix.platform }} arch=${{ matrix.arch }} target=${{ matrix.target }}
        env:
          PYTHON_BIN: python3
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            addons/lua-gdextension/build/libluagdextension.*

  test_distribution:
    name: Test ${{ matrix.name }}
    needs: [build_linux, build_windows, build_macos, build_web]
    runs-on: ${{ matrix.runner-os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner-os: ubuntu-latest
            godot-release: 4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
            godot-bin: ./Godot_v4.4-stable_linux.x86_64
          - name: Windows
            runner-os: windows-latest
            godot-release: 4.4-stable/Godot_v4.4-stable_win64.exe.zip
            godot-bin: ./Godot_v4.4-stable_win64.exe
          - name: macOS
            runner-os: macos-latest
            godot-release: 4.4-stable/Godot_v4.4-stable_macos.universal.zip
            godot-bin: ./Godot.app/Contents/MacOS/Godot
    env:
      GODOT_BIN: ${{ matrix.godot-bin }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Copy artifacts to build folder
        run: cp -r '${{ steps.download.outputs.download-path }}'/**/libluagdextension* addons/lua-gdextension/build
        env:
          MSYS_NO_PATHCONV: 1
      - name: Download Godot
        run: |
          curl --location https://github.com/godotengine/godot/releases/download/${{ matrix.godot-release }} --output godot.zip
          unzip godot.zip
      - name: Run tests
        run: |
          make test

  distribute_zip:
    name: Distribute zip
    needs: [build_linux, build_windows, build_macos, build_web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Copy artifacts to build folder
        run: |
          make copy-files-to-addon
          cp -r ${{ steps.download.outputs.download-path }}/**/libluagdextension* addons/lua-gdextension/build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lua-gdextension
          path: |
            LICENSE
            addons/lua-gdextension/**

