name: Test
on: [push, pull_request]
defaults:
  run:
    shell: bash

env:
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache

jobs:
  test_linux:
    name: Run tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            $SCONS_CACHE
          key: linux-x86_64-template_debug-test
      - name: Build artifact
        run: |
          scons
      - uses: vitorgus/setup-godot@v1
        with:
          godot-version: 4.1.1
          download-templates: false
      - name: Run tests
        run: |
          # Must run Godot editor at least once for it to generate .godot folder
          godot --editor --headless --quit --path test
          scons test

