name: Test
on: [push, pull_request]
defaults:
  run:
    shell: bash

env:
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache

jobs:
  test_linux:
    name: Run tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            $SCONS_CACHE
          key: linux-x86_64-template_debug-test
      - name: Build artifact
        run: |
          scons
      - name: Install Godot
        run: |
          curl --location $GODOT_RELEASE_URL --output godot.zip
          unzip godot.zip
          mv Godot_* godot
          touch _sc_
        env:
          GODOT_RELEASE_URL: https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_linux.x86_64.zip
      - name: Run tests
        run: |
          scons test
        env:
          GODOT_BIN: ./godot

